name = "lobby"
mc_version = "1.20.2"

[jar]
type = "paper"
build = "latest"

[variables]
PORT = "25565"

[launcher]
nogui = true
preset_flags = "Aikars"
eula_args = true

[options]
upload_to_mclogs = false
