[package]
name = "mcman"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ParadigmMC/mcman/"

[profile.release]
debug = false
strip = true
lto = "thin"

[dependencies]
anyhow = "1.0"
clap = "4.3"
console = "0.15"
dialoguer = "0.10"
futures = "0.3"
indicatif = "0.17"
java-properties = { git = "https://github.com/ParadigmMC/java-properties.git" }
regex = "1.8"
reqwest = { version = "0.11", features = ["json", "stream", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.6"
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread"] }
toml = "0.7"
walkdir = "2.3"
zip = "0.6"
