[package]
name = "mcman"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ParadigmMC/mcman/"


[dependencies]
anyhow = "1.0"
clap = "4.3"
console = "0.15"
futures = "0.3"
indicatif = "0.17"
java-properties = { git = "https://github.com/ParadigmMC/java-properties.git" }
regex = "1.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread"] }
toml = "0.7"
walkdir = "2.3"
