[package]
name = "mcman"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ParadigmMC/mcman/"


[dependencies]
clap = "4.3"
futures = "0.3"
indicatif = "0.17"
java-properties = "1.4.1"
regex = "1.8.1"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.28", features = ["macros", "rt", "rt-multi-thread"] }
toml = "0.7"
walkdir = "2"
