[package]
name = "mcman"
version = "0.1.0"
edition = "2021"


[dependencies]
bytes = "1.4.0"
clap = "4.3"
futures-core = "0.3.28"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.28.1", features = ["macros", "rt", "rt-multi-thread"] }
toml = "0.7"
