site_name: mcman
repo_url: https://github.com/ParadigmMC/mcman
repo_name: ParadigmMC/mcman
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
    - tutorials/getting-started.md
    - tutorials/importing-modpacks.md
    - tutorials/folder-structure.md
    - tutorials/building.md
    - tutorials/variables.md
  - Commands:
    - commands/index.md
    - init: commands/init.md
    - build: commands/build.md
    - run: commands/run.md
    - import <url/mrpack/packwiz>: commands/import.md
    - export <mrpack/packwiz>: commands/export.md
    - info: commands/info.md
    - pull: commands/pull.md
    - markdown: commands/markdown.md
    - env: commands/env.md
    - version: commands/version.md
  - Reference:
    - server.toml:
      - reference/server.toml.md
      - reference/world.md
      - reference/markdown-options.md
      - reference/server-launcher.md
      - reference/clientsidemod.md
    - Server Type:
      - reference/servertype/index.md
      - reference/servertype/vanilla.md
      - reference/servertype/fabric.md
      - reference/servertype/quilt.md
      - reference/servertype/papermc.md
      - reference/servertype/purpurmc.md
      - reference/servertype/bungeecord.md
      - reference/servertype/buildtools.md
    - Downloadable:
      - reference\downloadable\index.md
      - reference\downloadable\modrinth.md
      - reference\downloadable\curserinth.md
      - reference\downloadable\spigot.md
      - reference\downloadable\github-releases.md
      - reference\downloadable\jenkins.md
      - reference\downloadable\custom-url.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/server
  palette: 
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ParadigmMC/mcman