name = "CoolNetwork"
proxy = "proxy"
port = 25565

[servers.lobby]
port = 25566

[servers.game1]
port = 25567

[variables]
MADE_USING = "mcman"
MOTD = "Welcome to CoolNetwork!"

[markdown]
files = ["README.md"]
auto_update = false
