name = "game1"
mc_version = "1.20.2"

[jar]
type = "quilt"
loader = "latest"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
nogui = true
preset_flags = "aikars"
eula_args = true

[options]
upload_to_mclogs = false
