name = "spigot"
mc_version = "1.20.2"

[jar]
type = "buildtools"
software = "spigot"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "aikars"

[options]
upload_to_mclogs = false
