name = "quilt"
mc_version = "1.19.2"

[jar]
type = "quilt"
loader = "latest"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true

[[mods]]
type = "modrinth"
id = "create-fabric"
version = "wKEEi1qX"

[[mods]]
type = "modrinth"
id = "qsl"
version = "BTCxVi75"

[[mods]]
type = "modrinth"
id = "spark"
version = "XhFbpH8f"

[[mods]]
type = "jenkins"
url = "https://ci.lucko.me"
job = "LuckPerms"
build = "latest"
artifact = "Fabric"

[markdown]
files = ["README.md"]
auto_update = true

[options]
upload_to_mclogs = true
