name = "creative-anarchy"
mc_version = "1.20.1"

[jar]
type = "jenkins"
url = "https://ci.plex.us.org"
job = "Scissors/1.20.1"
build = "latest"
artifact = "first"

[variables]
PORT = "25565"

[launcher]
aikars_flags = true
proxy_flags = false
nogui = true
eula_args = true

[markdown]
files = ["README.md"]
auto_update = false
