on:
  push:
  pull_request:

name: Clippy and build
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/upload-artifact@v3
        with:
          name: mcman-${{ matrix.os }}
          path: target/release/mcman*
