name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu
        working-directory: ${{ github.workspace }}

      - name: Archive Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: mcman-linux
          path: target/x86_64-unknown-linux-gnu/release/mcman

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc
        working-directory: ${{ github.workspace }}

      - name: Archive Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: mcman-windows
          path: target/x86_64-pc-windows-msvc/release/mcman.exe
