# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile Windows
        id: compilewin
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: Compile Linux
        id: compilelinux
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compilewin.outputs.BUILT_ARCHIVE }}
            ${{ steps.compilelinux.outputs.BUILT_ARCHIVE }}
