on:
  push:
  pull_request:

name: Test Servers
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --quiet run --test
